name: Deploy
on:
  push:
    branches:
      - addshore-github-actions-for-upstream

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Explain
        run: |
          echo "Bump version, build, generate github release, push docker images and the docs"
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: ./builder.bash deploy-ci
