name: Deploy
on:
  branches-ignore:
    - '*'
#  branches:
#    - 'addshore-github-actions-for-upstream'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Explain
        run: |
          echo "Bump version, build, generate github release, push docker images and the docs"
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        run: ./builder.bash deploy-ci
